name: wage-education-analysis
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.9
  - pandas=2.2.3
  - numpy=2.0.2
  - matplotlib=3.9.4
  - seaborn=0.13.2
  - statsmodels=0.14.4
  - scikit-learn=1.6.1
  - jupyterlab
  - pip
  - pip:
      - ipykernel
